# Generated by Django 2.1.9 on 2019-06-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/aboutus/')),
                ('title', models.TextField()),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('resume_pdf', models.FileField(upload_to='uploaded/resume/')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suit_num', models.PositiveIntegerField(default=None)),
                ('floor_num', models.PositiveIntegerField(default=None)),
                ('street_num', models.PositiveIntegerField()),
                ('street_name', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
                ('postal_code', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_time', models.TimeField()),
                ('request_duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('logo_image', models.ImageField(upload_to='images/brand_logo/')),
                ('web_page_logo', models.ImageField(upload_to='images/brand_web_page_logo/')),
                ('title', models.TextField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('email', models.TextField()),
                ('facebook_url', models.URLField(default='na@na.com')),
                ('twitter_url', models.URLField(default='na@na.com')),
                ('linkedin_url', models.URLField(default='na@na.com')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_email', models.TextField(default='')),
                ('subject', models.TextField(default='')),
                ('msg', models.TextField(default='')),
                ('msg_time', models.TimeField()),
                ('file', models.FileField(upload_to='uploaded/attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=6)),
                ('telephone', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HoursOfOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday'), ('All', 'All Days')], default='Mon', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_desc', models.TextField()),
                ('self_webpage_link', models.URLField(default='na@na.com')),
                ('price', models.PositiveIntegerField()),
                ('duration_in_mins', models.IntegerField()),
                ('duration_in_hours', models.IntegerField()),
                ('main_pic', models.ImageField(upload_to='images/service/thumb/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/service/all/')),
                ('service_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Service')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TemporaryFileUpload',
            fields=[
                ('upload_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded/attachments/')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ContactNumber'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='service_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Service'),
        ),
    ]
